### ISSUE TITLE
Are emacs dependencies included in the install?

### ISSUE THREAD

**Issue by nimafazeli** [enko/EmacsChocolateyPackage#5]
Hi,
By looking at the package source I see that emacs dependencies are also included but I am not quite sure whether they get installed using `choco install emacs` or should I use a switch or something.
Thanks in advance for your clarification.

**Comment by enko** [comment]
Hi @nimafazeli,

yes they are included, at least partly. If you look at https://github.com/enko/EmacsChocolateyPackage/blob/master/tools/install.ps1 you can see these lines:

```
Install-ChocolateyZipPackage @DepsPackageArgs -specificFolder 'bin'
Install-ChocolateyZipPackage @DepsPackageArgs -specificFolder 'etc'
Install-ChocolateyZipPackage @DepsPackageArgs -specificFolder 'libexec'
Install-ChocolateyZipPackage @DepsPackageArgs -specificFolder 'ssl'
```

That means that the `bin`, `etc`, `libexec` and `ssl` folder of the deps are included.

You can see in the virus scan results on https://chocolatey.org/packages/Emacs that there the binaries included from the deps package, so that means the binary are included.

Hope That Helps

Tim

**Comment by nimafazeli** [comment]
Thanks for clarification
